"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](fg:#ffb59a)\
[ 󰣇  ](bg:#ffb59a fg:#55200a)\
[](bg:#e7beaf fg:#ffb59a)\
$directory\
[](fg:#e7beaf bg:#e7beaf)\
$git_branch\
$git_status\
[](fg:#e7beaf bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1a110e bg:#140c09)\
$time\
[ ](fg:#140c09)\
\n$character"""

[directory]
style = "fg:#442a20 bg:#e7beaf"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#442a20"
format = '[[ $symbol $branch ](fg:#442a20 bg:#e7beaf)]($style)'

[git_status]
style = "bg:#442a20"
format = '[[($all_status$ahead_behind )](fg:#442a20 bg:#e7beaf)]($style)'

[nodejs]
symbol = ""
style = "bg:#1a110e"
format = '[[ $symbol ($version) ](fg:#f1dfd9 bg:#1a110e)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#140c09"
format = '[[  $time ](fg:#ffdad6 bg:#140c09)]($style)'
