$background = rgb(181210)
$foreground = rgb(eedfdb)
$primary = rgb(ffb59a)
$secondary = rgb(ebbcac)
$tertiary = rgb(d4c877)
$error = rgb(ffb4ab)

$active_border = rgb(ffb59a)
$inactive_border = rgb(403735)