$background = rgb(101417)
$foreground = rgb(e0e3e8)
$primary = rgb(95cdf7)
$secondary = rgb(b7c9d9)
$tertiary = rgb(cec0e8)
$error = rgb(ffb4ab)

$active_border = rgb(95cdf7)
$inactive_border = rgb(363a3e)