$background = rgb(121315)
$foreground = rgb(e3e2e4)
$primary = rgb(abcae4)
$secondary = rgb(bcc8d3)
$tertiary = rgb(dbbce2)
$error = rgb(ffb4ab)

$active_border = rgb(abcae4)
$inactive_border = rgb(38393b)