[config]
# Global settings (mandatory)
default_mode = 'dark'
default_type = 'scheme-tonal-spot'
source_color_index = '0'

[templates.colors]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/ags/colors.css'

[templates.foot]
input_path = '~/.config/matugen/templates/foot.conf'
output_path = '~/.config/foot/colors.ini'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors/colors.conf'

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk.tmp"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk.tmp"
output_path = "~/.config/gtk-4.0/colors.css"
post_hook = "pkill -f xdg-desktop-portal-gtk; /usr/lib/xdg-desktop-portal-gtk & disown"

[templates.vesktop]
input_path  = "~/.config/matugen/templates/synapse.css"
output_path = "~/.config/vesktop/themes/synapse.css"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"